//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autocar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autocar()
        {
            this.Offre = new HashSet<Offre>();
        }
    
        public int id_Autocar { get; set; }
        public string description { get; set; }
        public string imagePath { get; set; }
        public string marque { get; set; }
        public string model { get; set; }
        public Nullable<int> id_Societe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offre> Offre { get; set; }
        public virtual Societe Societe { get; set; }
    }
}
