//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeAbonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandeAbonnement()
        {
            this.LigneDemande = new HashSet<LigneDemande>();
        }
    
        public int id_Demande { get; set; }
        public System.TimeSpan heure_Depart { get; set; }
        public System.TimeSpan heure_Arrivee { get; set; }
        public System.DateTime date_Demande { get; set; }
        public string description { get; set; }
        public int prix { get; set; }
        public System.DateTime date_Depart { get; set; }
        public System.DateTime date_Arrivee { get; set; }
        public int id_Client { get; set; }
        public int id_VilleDepart { get; set; }
        public int id_VilleArrivee { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneDemande> LigneDemande { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
    }
}
