//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Navette.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.LigneAbonnement = new HashSet<LigneAbonnement>();
        }
    
        public int id_Offre { get; set; }
        public System.DateTime date_Offre { get; set; }
        public System.TimeSpan heure_Depart { get; set; }
        public System.TimeSpan heure_Arrivee { get; set; }
        public string description { get; set; }
        public decimal prix { get; set; }
        public System.DateTime date_Depart { get; set; }
        public System.DateTime date_Arrivee { get; set; }
        public int nb_Abonnes_Voulus { get; set; }
        public int nb_Abonnes_Atteints { get; set; }
        public int id_Societe { get; set; }
        public int id_VilleArrivee { get; set; }
        public int id_VilleDepart { get; set; }
        public int id_Autocar { get; set; }
    
        public virtual Autocar Autocar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneAbonnement> LigneAbonnement { get; set; }
        public virtual Societe Societe { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
    }
}
